### ISSUE TITLE
[Request] Add a spanish source

### ISSUE THREAD

**Issue by Lait999** [StreamerApp/Streamer#22]
App works like a charm and iOS doesn’t have any app to watch movies in spanish.🙏🏻

**Comment by Lait999** [comment]
Maybe “playdede.com” (login needed) or “seriesyonkis.io”.
I have been using playdede for a year

**Comment by madrid2022ok** [comment]
https://movidy.pro/
https://olgply.com/
https://hydrawire.tv/
https://azmovies.app/
https://www.goojara.to/
