### ISSUE TITLE
Something went wrong. Try again later!

### ISSUE THREAD

**Issue by adithyan-js** [StreamerApp/Streamer#26]
I am from India. I installed this streamer ios using AltStore and since the time I have opened the app “Something went wrong. Try again later!” Error keeps coming. What is wrong? I am running ios 15.5

**Comment by RollinggThunder** [comment]
Can you add more sources which can work without issues from ISP please ?

**Comment by RollinggThunder** [comment]
Akwam.to runs fine but is in Arabic I guess
Cinenow says no results found
123 works fine after the recent update 
Flixtor works fine
HDFilme says no results found 9 
9anime works fine .

**Comment by RollinggThunder** [comment]
Also, some sources aren't consistent, like sometimes they work, but other times comes up as 'Something went wrong'

**Comment by RollinggThunder** [comment]
> @adithyan-js @RollinggThunder Can you try the latest release here https://github.com/StreamerApp/Streamer/releases/tag/1.1.5
> 
> I did some fixes to escape the ISP block

Doesn't work and even got worse I would say almost all the sources arent working now accept the Arabic one.
Same errors as before .

**Comment by yyyoh2021** [comment]
> @adithyan-js @RollinggThunder Can you try the latest release here https://github.com/StreamerApp/Streamer/releases/tag/1.1.5
> 
> I did some fixes to escape the ISP block

I would like to add a translation option
From subsites
or OpenSubtitles
Adding a source for movie sites
The user adds it himself
Like Arab or foreign movie sites like YIFY
The application is excellent, but its circulation is more frequent, it talks, it controls translation sites and movies

**Comment by RollinggThunder** [comment]
I absolutely agree with this ,app is super good and very clean and most usable app I've used for this purpose tbh but some more refinement is needed so that we can rely on it whenever we need to watch something,its now good but not reliable .
Looking forward to future updates.

**Comment by RollinggThunder** [comment]
> > @adithyan-js @RollinggThunder Can you try the latest release here https://github.com/StreamerApp/Streamer/releases/tag/1.1.5
> > 
> > I did some fixes to escape the ISP block
> 
> I would like to add a translation option
> From subsites
> or OpenSubtitles
> Adding a source for movie sites
> The user adds it himself
> Like Arab or foreign movie sites like YIFY
> The application is excellent, but its circulation is more frequent, it talks, it controls translation sites and movies

I absolutely agree with this ,app is super good and very clean and most usable app I've used for this purpose tbh but some more refinement is needed so that we can rely on it whenever we need to watch something,its now good but not reliable .
Looking forward to future updates.

**Comment by yyyoh2021** [comment]
We are waiting for updates for this amazing and fast app with great quality
And improving the problem for translation and adding more sites for movies. Thank you
Interested in Apple tv

**Comment by RollinggThunder** [comment]
Waiting for Update now and what it brings !!
