### ISSUE TITLE
The bottom bar doesnt disappear during playback

### ISSUE THREAD

**Issue by michaelbash** [StreamerApp/Streamer#29]
![image](https://user-images.githubusercontent.com/43926910/170828342-4eedf7c4-5b56-4cd1-a669-67bd26054118.png)

**Comment by yyyoh2021** [comment]
I would like to add a translation option
From subsites
or OpenSubtitles
Adding a source for movie sites
The user adds it himself
Like Arab or foreign movie sites like YIFY
The application is excellent, but its circulation is more frequent, it talks, it controls translation sites and movies

**Comment by yyyoh2021** [comment]
> @michaelbash Thank you for the report. I fixed in the latest release 1.1.6
> @yyyoh2021 I don't get what you want to say. Can you open a separate issue and add more details. Thank you

I mean
me as a viewer
I want translation sites and movies in the application
Do not prefer the next application in reality because some sites are blocked
Meaning, you add in the settings the option to add the translation site or the translation site by the user if it is blocked

**Comment by michaelbash** [comment]
> @michaelbash Thank you for the report. I fixed in the latest release 1.1.6 @yyyoh2021 I don't get what you want to say. Can you open a separate issue and add more details. Thank you

thanks u are awesome
