### ISSUE TITLE
Filename too long error in altstore 

### ISSUE THREAD

**Issue by subculture93** [StreamerApp/Streamer#34]
![95B55502-0C4D-4A68-BF9B-F3BEC84ECD9A](https://user-images.githubusercontent.com/35312282/172919458-6fbf06aa-5a33-4c60-b077-81aeeab1cadd.jpeg)

hello dev can you please fix this issue? 
musing iOS 15.5 on iPhone 13 pro

**Comment by michael1900** [comment]
So after kodi also this beautiful app can't be signed with altstore. The altstore dev is really awful. It's more than a year old that we are asking to him to solve a bug which prevents to sign kodi framework and nothing!
